import py_compile
import tempfile
import unittest
from pathlib import Path

from core.artifacts import json_artifact_path
from modules.end_to_end_automation.src.executor import CodeGenerator


class ExecutorTests(unittest.TestCase):
    def test_generate_pom_script_respects_headless_and_select_resolver(self):
        with tempfile.TemporaryDirectory() as tmp:
            run_dir = Path(tmp)
            plan_path = json_artifact_path(run_dir, "Execution_Plan_test.json")
            plan_path.write_text('{"base_url": "https://example.com", "plans": []}', encoding="utf-8")

            generator = CodeGenerator(ai_engine=None)
            script_path = generator.generate_pom_script({"run_dir": str(run_dir)}, plan_path, headless=False)
            content = script_path.read_text(encoding="utf-8")

            self.assertIn("HEADLESS = False", content)
            self.assertIn("def _resolve_select", content)
            self.assertIn("self._resolve_select", content)
            self.assertIn('input[name="{raw}"]', content)
            self.assertIn("def _attribute_token_locators", content)
            self.assertIn('[name*="{token}" i]', content)
            self.assertIn("JSON_DIR = RUN_DIR / \"JSON\"", content)
            self.assertIn("DEBUG_FILE = JSON_DIR / \"Execution_Debug.json\"", content)
            self.assertIn("EXECUTION_PLAN_FILE = JSON_DIR / \"Execution_Plan_test.json\"", content)
            self.assertIn("LEARNING_FILE = JSON_DIR / \"Execution_Learning.json\"", content)
            self.assertIn("CHECKPOINT_FILE = JSON_DIR / \"Execution_Checkpoints.json\"", content)
            self.assertIn("NETWORK_FILE = JSON_DIR / \"Execution_Network.json\"", content)
            self.assertIn("ANTI_HALLUCINATION_AUDIT_FILE = JSON_DIR / \"Anti_Hallucination_Audit.json\"", content)
            self.assertIn("ALLOW_LOW_ANTI_HALLU_ENV = \"QA_AI_ALLOW_LOW_ANTI_HALLU\"", content)
            self.assertIn("class ActionResolutionError", content)
            self.assertIn("class CheckpointRequiredError", content)
            self.assertIn("def check_execution_gate", content)
            self.assertIn("assert_title_contains", content)
            self.assertIn("assert_any_text_visible", content)
            self.assertIn("assert_network_seen", content)
            self.assertIn("assert_network_status_ok", content)
            self.assertIn("assert_graphql_ok", content)
            self.assertIn("assert_endpoint_allowlist", content)
            self.assertIn("assert_cross_origin_safe", content)
            self.assertIn("debug_entries.append", content)
            self.assertIn("def _iter_contexts", content)
            self.assertIn("page.frames", content)
            self.assertIn("def _fill_control", content)
            self.assertIn("def _resolve_upload_target", content)
            self.assertIn("set_input_files", content)
            self.assertIn('[contenteditable="true"]', content)
            self.assertIn("elif action_type == \"hover\"", content)
            self.assertIn("elif action_type == \"scroll\"", content)
            self.assertIn("elif action_type == \"dismiss\"", content)
            self.assertIn("elif action_type == \"wait_for_text\"", content)
            self.assertIn("capture_runtime_state", content)
            self.assertIn("learning_entries.append", content)
            self.assertIn("checkpoint_entries.append", content)
            self.assertNotIn("PHOTO_DIR", content)
            self.assertNotIn("page.screenshot", content)
            self.assertIn("def show_step_overlay", content)
            self.assertIn("__qa_agent_step_overlay__", content)
            self.assertIn("video.save_as", content)
            self.assertIn("context.close()", content)
            self.assertIn("STEP_DELAY_MS", content)
            self.assertIn("OVERLAY_LEAD_IN_MS", content)
            self.assertIn("OVERLAY_HOLD_MS", content)
            self.assertIn("def wire_network_capture", content)
            self.assertIn("network_entries.append", content)
            self.assertIn("def _container_candidate_locators", content)
            self.assertIn("def _memory_selector_candidates", content)
            self.assertIn("def _looks_like_password_field", content)
            self.assertIn("def _looks_like_username_field", content)
            self.assertIn("learned_path_hints", content)
            self.assertIn("expected_request_map", content)
            self.assertIn("network_policy", content)
            self.assertIn("def _cli_safe_text", content)
            self.assertIn("def safe_print", content)
            self.assertIn('step_text = str(action.get("step_text", "")).strip()', content)
            self.assertIn("def format_step_overlay", content)
            self.assertIn("engine.overlay_lead_in_ms", content)
            self.assertIn("engine.overlay_hold_ms", content)
            self.assertIn("def _scoped_attribute_token_locators", content)
            self.assertIn("prefer_last=False", content)
            self.assertNotIn('candidates.append((container.locator(search_selector), f"container-field:{hint}"))', content)
            self.assertIn('text = text.replace(source, target)', content)
            self.assertIn('safe_print(f"Plans found: {len(test_plans)}")', content)
            self.assertIn('save_json(RESULT_FILE, {"results": [{"id": "RUN_GATE"', content)
            self.assertIn('"fact_ids": list(plan.get("scenario_grounding", {}).get("fact_ids", []))', content)
            self.assertIn('"grounding_score": float(plan.get("scenario_grounding", {}).get("score", 0.0) or 0.0)', content)
            py_compile.compile(str(script_path), doraise=True)


if __name__ == "__main__":
    unittest.main()
